import sys
import os
import re
import math

Values=[]

totalActualSpamFile=0
totalActualHamFile=0
totalPredSpamFile=0
totalPredHamFile=0

#Here output.txt is the outfile generated by per_classify script

with open('output.txt', "r", encoding="latin1") as fil:
    for f in fil:
        val=f.strip().split(' ')
        predictedTag=val[0]
        if (predictedTag == "spam"):
            totalPredSpamFile +=1
        else:
            totalPredHamFile += 1
        path=val[1].split('/')
        if (path[len(path) - 2] == "spam"):
            actualTag="spam"
            totalActualSpamFile +=1
        else:
            actualTag="ham"
            totalActualHamFile +=1

        Values.append((predictedTag,actualTag))

#print(Values)

def checkScores(values):
    commSpam = 0
    commHam = 0
    for v in values:
        #print(v)
        if (v[0] == v[1] == "spam"):
            commSpam +=1
        elif(v[0] == v[1] == "ham"):
            commHam +=1
    return (commSpam,commHam)


intersectSpam,intersectHam=checkScores(Values)

precisionHam=intersectHam/totalPredHamFile
recallHam=intersectHam/totalActualHamFile
fscoreHam = 2 * precisionHam * recallHam / (precisionHam + recallHam)
print("[HAM]","Precision:",precisionHam,",","Recall:",recallHam,",","FScore",fscoreHam)

precisionSpam= intersectSpam/totalPredSpamFile
recallSpam= intersectSpam/totalActualSpamFile
fscoreSpam = 2 * precisionSpam * recallSpam / (precisionSpam + recallSpam)
print("[SPAM]","Precision:",precisionSpam,",","Recall:",recallSpam,",","FScore",fscoreSpam)

